server:
  port: 8092
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3316/inventory_service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

